<?php
/**
 * @file
 * Module file for Remove Generator.
 */

/**
 * Implements hook_enable().
 */
function remove_generator_enable() {
  drupal_set_message(t('The Generator META tag has been removed.'));
}

/**
 * Implements hook_disable().
 */
function remove_generator_disable() {
  drupal_set_message(t('The Generator META tag has been restored.'));
}

/**
 * Implements hook_html_head_alter().
 */
function remove_generator_html_head_alter(&$head_elements) {
  // Remove Generator META tag.
  if (isset($head_elements['system_meta_generator'])) {
    unset($head_elements['system_meta_generator']);
  }
}

/**
 * Implement hook_metatag_info_alter().
 * @param array $info
 */
function remove_generator_metatag_info_alter(&$info) {
  // Explain why the generator is not rendered
  $info['tags']['generator']['label'] = t('Generator (Disabled by "Remove Generator" module)');
  
// And disable the tag by means of a fake classname.
  $info['tags']['generator']['class'] = 'ImaginaryKillGeneratorMetatagClass';
}